### ISSUE TITLE
This code made my computer melt...

### ISSUE THREAD

**Issue by cmshobe** [Glader011235/Coral#1]
I don't know what happened. I was settled in, watching Buffy the Vampire Slayer re-runs and editing this code for kicks and giggles, and then all of a sudden my computer crossed the liquidus and became simply a slurry of silver goop with some shreds of hip bumper stickers still readable within it.

I recommend that you only run this code while standing in a walk in freezer because this could happen to YOU!

**Comment by Glader011235** [comment]
Hahahahaha wtf

**Comment by Glader011235** [comment]
Thank you for your feedback. I have remotely altered the composition of your lappy, such that it now requires pressures greater than those possible on earth in order to cross the liquidus. 
This issue is now closed.
